### ISSUE TITLE
Use POST requests to create resources

### ISSUE THREAD

**Issue by pedrorohr** [murillocg/goleador#11]
GET, POST and DELETE requests have already been mapped for /jogadores and /partidas endpoints by @murillocg.

PUT requests allow the user interface to insert new data into the database.

**Comment by murillocg** [comment]
You should use POST to save and update resources. This is a project definition.
So, I believe the code in front end, just like backend, keep simple, less if conditions, duplicate code or methods, etc.
What do you think, @pedrorohr?

**Comment by pedrorohr** [comment]
I've been reading about it and apparently [it's a gray area](http://stackoverflow.com/questions/630453/put-vs-post-in-rest).
So, if it's a project definition, there's no need to say more.

I'm gonna update the title and implement this definition on the front end.

**Comment by pedrorohr** [comment]
I think we need to handle POST requests to update resources on our back end too. @murillocg 
It looks like we only handle POST requests for URIs without id.
