### ISSUE TITLE
Project build taking too long

### ISSUE THREAD

**Issue by murillocg** [murillocg/goleador#17]
Before merging the PR #12, the project building was taking [1 minute](https://travis-ci.org/murillocg/goleador/builds/221758095).
Now, it's taking [6 minutes!!](https://travis-ci.org/murillocg/goleador/builds/222924976).

I suspect the following directory `C:\projetos\goleador\src\main\webapp\node_modules` has something to do with it, because it is too big (~ 200MB) and it has a lot of small files.

**Comment by pedrorohr** [comment]
The following steps are taking more time:
~110s mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
~80s mvn clean cobertura:cobertura coveralls:report
~70s mvn clean package docker:build
~25s building image
~5s tests

The times above are the difference between the logs.

**Comment by murillocg** [comment]
We can temporary remove the coveralls step, but see the time to build by maven before:
~9s mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
~32s mvn clean package docker:build

**~23% of actual time.** 

**There is still something wrong!**

**Comment by pedrorohr** [comment]
Heroku maintains a cache that stores node_modules.
This cache is persisted between builds.
It is an option.

https://devcenter.heroku.com/articles/nodejs-support#cache-behavior

**Comment by pedrorohr** [comment]
Yarn [claims to be much faster and reliable than its predecessor](https://www.berriart.com/blog/2016/10/npm-yarn-benchmark/).

Maybe we can start using it instead of npm.
Take a look at this [performance comparison](https://yarnpkg.com/en/compare).

**Comment by murillocg** [comment]
Ohh my god!
Maybe that's why JHipster chose it.
Living and learning with the **opensource world**!
